steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh ubuntu@35.225.36.72 --zone=us-central1-a --command='/bin/sh /home/ubuntu/pull.sh'
