
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkins
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 4
  startegy:
    rollingupdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: nitintbi/node-ci-cd:latest
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: jenkins
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
